# Generated by Django 5.2.4 on 2025-07-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
