# Generated by Django 5.2.4 on 2025-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="zabee", max_length=30),
            preserve_default=False,
        ),
    ]
