# Generated by Django 5.2.4 on 2025-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_option",
        ),
        migrations.AddField(
            model_name="option",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
