# Generated by Django 5.2.4 on 2025-07-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_remove_question_correct_option_option_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
