# Generated by Django 5.2.4 on 2025-07-21 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0003_exam_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"]},
        ),
    ]
