# Generated by Django 5.2.4 on 2025-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0004_alter_question_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
