# Generated by Django 5.2.4 on 2025-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
